export EDITOR=vim
export PS1="\n\w\n\$ "
export TERM=xterm-256color

alias gb="git branch"
alias gg="git grep"
alias gs="git status"
alias ga="git add"
alias gd="git diff"
alias gc="git commit"
alias gp="git push"
alias gms="git merge --squash"
alias gco="git checkout"
alias gff="git pull --ff-only"
alias gpr="git pull --rebase"


alias ls="ls --color=auto"

