export EDITOR=vim
export PS1="\n\w\n\$ "
export TERM=xterm-256color

alias gb="git branch"
alias gg="git grep"
alias gs="git status"
alias ga="git add"
alias gd="git diff"
alias gc="git commit"
alias gp="git push"
alias gms="git merge --squash"
alias gco="git checkout"
alias gff="git pull --ff-only"
alias gpr="git pull --rebase"


alias ls="ls -G"

if [ -e $HOME/.bashrc_local ]; then
  source $HOME/.bashrc_local
fi

export PATH=$HOME/scripts:$HOME/configs/scripts:$PATH

export ANDROID_HOME=$HOME/android
export ANDROID_NDK_HOME=$HOME/opt/android-ndk-r8e
export ANDROID_PLATFORM=${ANDROID_NDK_HOME}/platforms/android-14
export RMSDK_ROOT=$HOME/work/rmsdk
export PATH=${ANDROID_NDK_HOME}/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86_64/bin:$PATH
