se noswapfile
se nowritebackup
se nobackup
se ts=2
se tw=0
se sw=2
se expandtab
se nowrap
se hidden
se nocompatible
se smartcase
se scrolloff=5
se undolevels=10000
se encoding=utf-8
se cin
se nosi
se noai

filetype plugin indent on
syntax on

se list
se listchars=trail:·
se number
se nohlsearch
se nojoinspaces
se guicursor+=a:blinkon0

nmap ; :

color morning

silent call pathogen#infect()

if has("gui_running")
  se guioptions=a
endif
